apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yc4kil225-nodejs
  janus-idp.io/tekton: yc4kil225-nodejs
  backstage.io/kubernetes-id: yc4kil225-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yc4kil225-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
